spring:
  application:
    name: microservice2

  datasource:
    url: jdbc:h2:mem:microservice2db
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        connection:
          autocommit: false
        format_sql: true

server:
  port: 8081
  ssl:
    enabled: true
    key-alias: microservice1
    key-store: classpath:keystore.jks
    key-store-password: password
    key-store-type: JKS

microservice1:
  hello-url: https://MICROSERVICE1/hello

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: https://localhost:8761/eureka/