services:
  microservice1:
    build: microservice1
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  microservice2:
    build: microservice2
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker