services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservice-net

  eureka-server:
    build: infrastructures/eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservice-net

  config-server:
    build: infrastructures/config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net

  api-gateway:
    build: modules/api-gateway
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net

  product-service:
    build: modules/product-service
    ports:
      - "8082:8082"
      - "9090:9090"  # gRPC
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net

  customer-service:
    build: modules/customer-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge
