spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://MICROSERVICE1
          predicates:
            - Path=/microservice1/**
          filters:
            - RoleValidationFilter
        - id: swagger-ui
          uri: lb://MICROSERVICE1
          predicates:
            - Path=/openapi/**
        - id: microservice2
          uri: lb://MICROSERVICE2
          predicates:
            - Path=/microservice2/**

server:
  port: 8086

role-validation:
  enabled: false
  required-role: microservice1
  client-name: myclient

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

