spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:"
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false
      retry:
        initial-interval: 180000
        multiplier: 1.3
        max-interval: 1000
        max-attempts: 200
