spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: lb://MICROSERVICE1
          predicates:
            - Path=/microservice1/**
        - id: microservice2
          uri: lb://MICROSERVICE2
          predicates:
            - Path=/microservice2/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

