spring:
  application:
    name: spring-admin-server
  profiles:
    active:
      - dev

server:
  port: 7070
  servlet:
      context-path: /admin

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}