spring:
  config:
    import: "configserver:"
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8888
      name: product-service
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20